---
# tasks file for mongodb
- name: Add MongoDB repository GPG key
  apt_key:
    url: 'https://pgp.mongodb.com/server-7.0.asc'
    state: present

- name: Add MongoDB repository
  apt_repository:
    repo: 'deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse'
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: yes