---
# tasks file for monitoring_pometheus_grafana
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present

- name: Create  directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/prometheus
    - /opt/grafana

- name: Copy Prometheus configuration
  copy:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Copy Docker Compose file
  copy:
    src: docker-compose.yml
    dest: /opt/docker-compose.yml

- name: Start Prometheus and Grafana containers
  command: docker-compose -f /opt/docker-compose.yml up -d