---
# tasks file for ELK
- name: Add Elastic APT repository
  apt_repository:
    repo: "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main"
    state: present
    filename: elastic-8.x.list

- name: install Elastic apt
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nginx
    - elasticsearch
    - kibana
    - logstash

- name: Copy conf kibana
  template:
    src: templates/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: kibana
    group: kibana
    mode: 0644
  notify: Restart Kibana


- name: Copy conf nginx
  template:
    src: templates/default.j2
    dest: /etc/nginx/sites-available/default
    mode: 0644
  notify: Restart Nginx

- name: Copy conf file logstash
  template:
    src: "{{ item }}"
    dest: /etc/logstash/conf.d/{{ item | regex_replace('\.j2$', '') | regex_replace('.*/', '') }}
    mode: 0644
  loop:
    - templates/input.conf.j2
    - templates/filter.conf.j2
    - templates/output.conf.j2
  notify: Restart Logstash

