---
# tasks file for zabbix
- name: Install prerequisites
  apt:
    name:
      - apache2
      - php
      - php-mysql
      - php-mbstring
      - php-bcmath
      - php-xml
      - php-gd
      - php-ldap
      - mariadb-server
      - mariadb-client
    state: present
    update_cache: yes

- name: Download and install Zabbix Server
  apt:
    deb: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4%2Bubuntu22.04_all.deb"
    update_cache: yes
    state: present

- name: Install Zabbix Server packages
  apt:
    name:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-apache-conf
      - zabbix-sql-scripts
    state: present
    update_cache: yes

- name: Configure Zabbix Server
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
  ignore_errors: true
  notify: Restart Zabbix Server